apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argocd
    repoURL: 
    targetRevision: 
    helm:
    valueFiles:
    - values.yaml
  destination:
    name: "in-cluster"
    namespace: argocd
