global:
  domain: argocd.internal.coffeeandacomputer.com
server:
  ingress:
    enabled: true
    ingressClassName: nginx 
configs:
  params:
  server.insecure: true
  repositories:
    private-repo:
      url: https://github.com/noliverio/cluster-infrastructure