apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  {{ template "common-app-metadata" . }}
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.5.14
    helm:
      valuesObject:
        global:
          domain: argocd.internal.coffeeandacomputer.com
        server:
          ingress:
            enabled: true
            ingressClassName: nginx 
        configs:
          params:
          server.insecure: true
          repositories:
            url: https://github.com/noliverio/cluster-infrastructure
  {{ template "default-sync-policy" . }}
  destination:
    name: "in-cluster"
    namespace: argocd
