apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  {{ template "common-app-metadata" . }}
spec:
  project: default
  source:
    chart: cilium
    repoURL: quay.io/cilium/charts
    targetRevision: 1.19.4
    helm:
      valuesObject:
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  destination:
    name: "in-cluster"
    namespace: kube-system
  {{ template "default-sync-policy" . }}
