apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
{{- include "common-app-metadata" | nthindent 2 -}}
spec:
  project: default
  source:
    chart: cilium
    repoURL: quay.io/cilium/charts/cilium
    targetRevision: 1.19.4
    helm:
      valuesObject:
        hubble:
          relay:
            enabled: true
          ui:
            enabled: true
  destination:
    name: "in-cluster"
    namespace: cilium
 {{- include "default-sync-policy" | nthindent 2 -}}
