apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.spec.argoNameSpace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: kubernetes.github.io/ingress-nginx
    # targetRevision: 
    helm:
    valueFiles:
    - values.yaml
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
