apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
{{- include "common-app-metadata" | nindent 2 -}}
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: kubernetes.github.io/ingress-nginx
    targetRevision: 4.15.1
    helm:
      valueFiles:
      - ingress-nginx-values.yaml
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
{{- include "default-sync-policy" | nindent 2 -}}
