apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  {{ template "common-app-metadata" . }}
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: kubernetes.github.io/ingress-nginx
    targetRevision: 4.15.1
    helm:
      valueFiles:
      - ingress-nginx-values.yaml
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
  {{ template "default-sync-policy" . }}
